#!/bin/bash

# want to know more about user-defined/built-in shell functions/aliases, use cv
$ cv
$ cv !!

# while read ln; do if ! grep -q $ln bfile; then echo $ln; fi; done < afile
while read ln; 
do 
  if ! grep -q $ln bfile
  then 
    echo $ln
  fi
done < afile

# to unset alias and functions in zsh
unalias alias-name
unset -f function-name

# vim: filetype=bash
